spring.datasource.url=jdbc:h2:mem:myy803db;MODE=MySQL;NON_KEYWORDS=YEAR
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:DDL/schema.sql
spring.sql.init.data-locations=classpath:DDL/testdata.sql